# Generated by Django 4.0.3 on 2022-03-18 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chapters', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explains', models.TextField(blank=True, null=True)),
                ('importants', models.TextField(blank=True, null=True)),
                ('regulars', models.TextField(blank=True, null=True)),
                ('reminders', models.TextField(blank=True, null=True)),
                ('attentions', models.TextField(blank=True, null=True)),
                ('questions', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('voice', models.FileField(blank=True, null=True, upload_to='voices/%Y/%m/%d')),
                ('rtl', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='chapters.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
