# Generated by Django 4.0.3 on 2022-03-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='attentions',
        ),
        migrations.RemoveField(
            model_name='point',
            name='explains',
        ),
        migrations.RemoveField(
            model_name='point',
            name='importants',
        ),
        migrations.RemoveField(
            model_name='point',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='point',
            name='regulars',
        ),
        migrations.RemoveField(
            model_name='point',
            name='reminders',
        ),
        migrations.AddField(
            model_name='point',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
