# Generated by Django 4.0.3 on 2022-03-31 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_remove_point_attentions_remove_point_explains_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='rtl',
        ),
    ]
