# Generated by Django 4.0.3 on 2022-04-04 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('points', '0003_remove_point_rtl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmarks', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='favorite',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='points.point'),
        ),
    ]
