# Generated by Django 4.0.3 on 2022-05-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_active_book_category_book_price_book_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.CharField(default='0+0', max_length=255),
        ),
    ]
