# Generated by Django 4.0.3 on 2022-03-17 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chapters', '0002_chapter_user_alter_chapter_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to=settings.AUTH_USER_MODEL),
        ),
    ]
