# Generated by Django 4.0.3 on 2022-03-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام و نام خانوادگی')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='معرفی')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن')),
                ('active', models.BooleanField(default=False, verbose_name='فعال است؟')),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('manager', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=6)),
                ('api_key', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
