# Generated by Django 4.0.3 on 2022-03-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0003_phoneotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='validated',
            field=models.BooleanField(default=False, help_text='We walidate this via a class in views.'),
        ),
    ]
