# Generated by Django 4.0.3 on 2022-03-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0004_phoneotp_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_login',
            field=models.BooleanField(default=False),
        ),
    ]
