# Generated by Django 4.0.3 on 2022-04-10 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name': 'study', 'verbose_name_plural': 'studies'},
        ),
    ]
