# Generated by Django 4.0.3 on 2022-04-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_alter_study_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ['id'], 'verbose_name': 'study', 'verbose_name_plural': 'studies'},
        ),
        migrations.AlterField(
            model_name='study',
            name='function',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
